//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.22 at 01:31:49 PM EEST
//


package models;


import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KnifesDesc }
     */
    public KnifesDesc createKnifeDesc() {
        return new KnifesDesc();
    }

    /**
     * Create an instance of {@link KnifesDesc.KnifeVisual }
     */
    public KnifesDesc.KnifeVisual createKnifeDescKnifeVisual() {
        return new KnifesDesc.KnifeVisual();
    }

    /**
     * Create an instance of {@link KnifesDesc.KnifeVisual.KnifeHandle }
     */
    public KnifesDesc.KnifeVisual.KnifeHandle createKnifeDescKnifeVisualKnifeHandle() {
        return new KnifesDesc.KnifeVisual.KnifeHandle();
    }

    /**
     * Create an instance of {@link Knifes }
     */
    public Knifes createKnifes() {
        return new Knifes();
    }

    /**
     * Create an instance of {@link KnifesDesc.KnifeVisual.KnifeBlade }
     */
    public KnifesDesc.KnifeVisual.KnifeBlade createKnifeDescKnifeVisualKnifeBlade() {
        return new KnifesDesc.KnifeVisual.KnifeBlade();
    }

    /**
     * Create an instance of {@link KnifesDesc.KnifeVisual.KnifeHandle.Wood }
     */
    public KnifesDesc.KnifeVisual.KnifeHandle.Wood createKnifeDescKnifeVisualKnifeHandleWood() {
        return new KnifesDesc.KnifeVisual.KnifeHandle.Wood();
    }

}